### PR TITLE
Use 'foo-bar-org' for the organization name placeholder instead of 'xwp'

### LINKED ISSUE #87: Organization name placeholder should be different than `xwp`
## Bug Description

During a new plugin initialization, when executing `init-plugin.sh`, [each occurrence of the `xwp` string is replaced with the `org_lower` variable](https://github.com/xwp/wp-foo-bar/blob/develop/init-plugin.sh#L104):

```sh
git grep -lz "xwp" | xargs -0 sed -i '' -e "s/xwp/$org_lower/g"
```

When the organization name is different than `xwp`, we're running into some unexpected issues. In such case e.g. `composer.json` and `package.json` files get corrupted like this:

```diff
  "require-dev": {
    [ ... ],
-   "xwp/wordpress-tests-installer": "*",
-   "xwp/wp-dev-lib": "*"
  },
  "require-dev": {
    [ ... ],
+   "acme/wordpress-tests-installer": "*",
+   "acme/wp-dev-lib": "*"
  },
``` 

This leads to initialization errors and not being able to complete the setup.

## Expected Behaviour

Some other organization name placeholder should be used instead of `xwp` string. This could be something like `foo-bar-org`.

The `xwp` string should still be used wherever it's intended and should not be replaced throughout the initialization process.

## Steps to reproduce

1. Clone the repo 
2. Go to `cd wp-foo-bar` folder
3. Start the initialization: `./init-plugin.sh`
4. When asked for organization name, provide something else than `xwp` (e.g. leave empty)
5. Observe errors in the initialization process. See the e.g. `composer.json` and `package.json` files contents

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by delawski**
## Summary

This PR searches and replaces the organization's name along with the repo slug as a whole. This is to prevent initialization errors described in #86 

Fixes #87 

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/xwp/wp-foo-bar/issues) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/xwp/wp-foo-bar/contributing.md#scripts).
- [x] My code follows the [Contributing Guidelines](https://github.com/xwp/wp-foo-bar/contributing.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by derekherman** [comment]
Just peeked quickly at the code changes in the PR and I think we should handled this slightly different. Instead of creating a fake org that doesn’t match the actual GitHub path and replacing just xwp I think it should replace the org and plugin slug together. This means we need to use an alternative find and replace approach for that string, which includes the org and slug.

**Comment by delawski** [comment]
It makes sense to me. I've updated the PR so now we're replacing the organization name along with the repo slug. This approach seems way more graceful and doesn't cause the initialization script errors. Please have another look.

**Comment by derekherman** [comment]
We should probably leave the slug replacement in but insert it after the new combined replacement as there are some places I believe that the slug exists without the org. Maybe double check that assumption.

**Comment by delawski** [comment]
I checked if the second replacement is needed. It seems that the slug always comes along with the organization name (I haven't been able to find `wp-foo-bar` in the generated plugin directory). Based on that, I think it's safe to remove the second replacement as proposed in the PR.

**Pull request merged**
