### PR TITLE
Upgrade Packages

### PR DESCRIPTION
**Pull request by valendesigns**

### CODE REVIEW

**Comment by kopepasah** [comment]
@valendesigns just curious as to the reason for the downgraded past the non-stable (1.0.0) version.

**Comment by valendesigns** [comment]
It causes the build to fail

**Comment by valendesigns** [comment]
All the packages are using the previous `0.4.0` branch and by reverting the change this will pass.

https://travis-ci.org/xwp/wp-foo-bar/jobs/140707788

**Comment by westonruter** [comment]
If the peer packages are updated to their latest versions, will Grunt 1.0.x then work again?

> npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer grunt-checktextdomain@1.0.1 wants grunt@>=0.4.1
> npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5
> npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-shell@1.3.0 wants grunt@>=0.4.0
> npm ERR! peerinvalid Peer grunt-wp-deploy@1.1.0 wants grunt@~0.4.1
> npm ERR! peerinvalid Peer grunt-wp-i18n@0.5.4 wants grunt@>=0.4.0

**Comment by valendesigns** [comment]
It seems if we removed grunt-deploy then we might be able to use the new 1.0.x branch.

**Comment by kopepasah** [comment]
@valendesigns I assume you mean `grunt-wp-deploy` and, if so, we could probably update that packages, as it seems the developer has push recent changes to account for the Grunt release.

**Comment by valendesigns** [comment]
@kopepasah Good catch! I've upgraded all the packages. Should be good now. We'll see when it's merged into master if the build passes.

**Pull request merged**
